#!/usr/bin/env python

import os
import datetime
import time
from camera import Camera
from util import ParsingArguments


if __name__ == '__main__':

    final_config = ParsingArguments()

    # final stuff
    creds = {}
    creds['ip'] = final_config['ip']
    creds['username'] = final_config['username']
    creds['password'] = final_config['password']
    iterations = final_config['iterations']
    outputdir = final_config['outputdir']

    cam = Camera(creds)

    # setup enviroment
    cam.manual_daynight()
    cam.anon_snapshot(enable=True)

    modes = ['night', 'day']
    now_dir = ''

    for iteration in xrange(0, iterations):
        for mode in modes:
            cam.daynight(mode)

            now = datetime.datetime.now()
            dirname = "{outputdir}/{year}-{month}-{day}/".format(
                outputdir=outputdir, year=now.year,
                month=now.month, day=now.day)
            filename = "{hour}-{min}-{second}-{mode}.jpg".format(
                hour=now.hour, min=now.minute, second=now.second, mode=mode)

            if now_dir != dirname:
                if not os.path.exists(dirname):
                    os.makedirs(dirname)
                now_dir = dirname

            image = cam.snapshot()
            image.save(dirname + "/" + filename)
            time.sleep(1)

    cam.auto_daynight()
